CC = g++
CFLAGS = -g -c -Wall
LDFLAGS =
SOURCES = client.cpp tcpstream.cpp tcpconnector.cpp
INCLUDES = -I.
OBJS = $(SOURCES:.cpp=.o)
TARGET = client

all: $(SOURCES) $(TARGET)

$(TARGET): $(OBJS)
	$(CC) $(LDFLAGS) $(OBJS) -o $@

.cpp.o:
	$(CC) $(CFLAGS) $(INCLUDES) $< -o $@

clean:
	rm -rf $(OBJS) $(TARGET)
